language: python

python:
  - "3.6"

services:
- postgresql

env:
  global:
    - Testingenv = "EnvTests"

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
  - pip install pytest

before_script:
  - psql -c 'create database storemanagerdb;' -U postgres
  - psql -c 'create database testdb;' -U postgres

script:
  - pytest tests --cov=api --cov-report term-missing

after_success:
- coveralls